version: "2"
services:
        airsonic:
         restart: always
         image: airsonic/airsonic:${AIRSONIC_VERSION}
         mem_limit: 1GB
         volumes:
             - ${AIRSONIC_STATE_FOLDER}:/airsonic/data
             - ${AIRSONIC_MUSIC_FOLDER}:/airsonic/music
             - ${AIRSONIC_PLAYLISTS_FOLDER}:/airsonic/playlists
             - ${AIRSONIC_PODCASTS_FOLDER}:/airsonic/podcasts
         environment:
              - "TZ=${TIMEZONE}"
              - VIRTUAL_HOST=music.${BASE_HOST_NAME}
              - LETSENCRYPT_HOST=music.${BASE_HOST_NAME}
              - LETSENCRYPT_EMAIL=${EMAIL}

        rutorrent:
         restart: always
         image: linuxserver/rutorrent:${RUTORRENT_VERSION}
         mem_limit: 3GB
         ports:
              - "${RUTORRENT_BACKEND_PORT}:5000"
              - "${RUTORRENT_LISTENING_PORT}:51413"
              - "${RUTORRENT_DHT_PORT}:6881"
         volumes:
              - ${RUTORRENT_CONFIG_DIR}:/config
              - ${RUTORRENT_DOWNLOAD_DIR}:/downloads
         environment:
              - "TZ=${TIMEZONE}"
              - "PGID=${RUTORRENT_DOWNLOAD_GID}"
              - "PUID=${RUTORRENT_DOWNLOAD_UID}"
              - VIRTUAL_HOST=torrent.${BASE_HOST_NAME}
              - VIRTUAL_PORT=80
              - LETSENCRYPT_HOST=torrent.${BASE_HOST_NAME}
              - LETSENCRYPT_EMAIL=${EMAIL}

        gitlab:
         restart: always
         image: 'gitlab/gitlab-ce:${GITLAB_VERSION}'
         hostname: 'gitlab.${BASE_HOST_NAME}'
         mem_limit: 3GB
         environment:
           LETSENCRYPT_HOST: 'gitlab.${BASE_HOST_NAME}'
           LETSENCRYPT_EMAIL: '${EMAIL}'
           VIRTUAL_HOST: 'gitlab.${BASE_HOST_NAME}'
           VIRTUAL_PORT: '80'
           GITLAB_OMNIBUS_CONFIG: |
             external_url 'https://gitlab.${BASE_HOST_NAME}'
             nginx['listen_port'] = 80
             nginx['listen_https'] = false
             nginx['proxy_set_headers'] = {  "X-Forwarded-Proto" => "https", "X-Forwarded-Ssl" => "on" }
             prometheus_monitoring['enable'] = false
             postgresql['shared_buffers'] = "512MB"
             sidekiq['concurrency'] = 5 
             unicorn['worker_processes'] = 3
         ports:
           - '8022:80'
         volumes:
           - '${GITLAB_STATE_FOLDER}:/etc/gitlab'
           - '${GITLAB_LOGS_FOLDER}:/var/log/gitlab'
           - '${GITLAB_DATA_FOLDER}:/var/opt/gitlab'

        nginx-proxy:
         restart: always
         image: jwilder/nginx-proxy
         mem_limit: 512MB
         ports:
          - "80:80"
          - "443:443"
         volumes:
          - /srv/docker/nginx/certs:/etc/nginx/certs:ro
          - /etc/nginx/vhost.d
          - /usr/share/nginx/html
          - /var/run/docker.sock:/tmp/docker.sock:ro

        nginx-proxy-companion:
         image: jrcs/letsencrypt-nginx-proxy-companion
         mem_limit: 100MB
         volumes:
          - /srv/docker/nginx/certs:/etc/nginx/certs:rw
          - /var/run/docker.sock:/var/run/docker.sock
         volumes_from:
          - nginx-proxy
